// import type { NextPage } from 'next'
/* eslint-disable @next/next/no-img-element */

import React,{Fragment} from 'react'
import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import { styled,globalCss,css } from '@stitches/react'
import HeaderComp from 'components/HeaderComp'
import { Box } from 'ui/box/box'
// import { Grid } from 'ui/grid/Grid'
// import { GridItem } from 'ui/grid/GridItem'
import { Flex } from 'ui/flex/Flex'
import { P, Subheader, Text } from 'ui/text/Text'
import { Button } from 'ui/button/Button'
import { Container } from 'ui/container/Container'
import { Main, Section, Span, Sup } from 'ui/special-divs/speacial'
import Features from 'components/Features'
import { I } from 'ui/icon/I'

const Home = () => {
  
  return (
   <Fragment>
     
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Wrapper>
<Main className='main'>
<HeaderComp/>
<Box className='banner' css={{display:"flex",  alignItems:"center", justifyContent:"center"}}>
<Container css={{display:"flex",}}>
<Box className='dgrid' >
  <Box>
  <Flex direction={'column'}>
    <Text css={{marginBottom:0}} >Give Your Child A 
Chance To Be Unique</Text>
  <P css={{paddingBottom:"30px", paddingTop:'15px', width:"75%"}}> Experts agree that a child’s personality doesn’t fully form until they are in elementary school. <br/> 
<Span style={{color:"#8FBF26"}}>Sign in </Span>to enroll your child</P>
  <Flex css={{columnGap:'$6', }}>
    <Button color={'Primary'}>Sign Up</Button> <Button color={'Primary'} css={{backgroundColor:"$special2"}}>Learn more</Button>
  </Flex>
  
</Flex>
  </Box>
  <Box></Box>

</Box>
</Container>
<Box className='hero-blur' css={{}}></Box>
</Box>
</Main>
<Section className='home2'>
  <Box></Box>
  <Container css={{mt:"10.1rem",   }}>
    <Box className='dgrid' >

      <Box>
      <Box className="home2imagesholder">
                  <Box className="image-2">
                    <img src="/images/mask1.png" alt="" className="image2-1" />
                    <img  src="/images/girl.png" alt="" className="girl1" />
                    <Box className="circle"></Box>                  
                  </Box>
                </Box>
      </Box>
      <Box css={{ display:"flex",mt:0,pt:0,  }}>
       <Box> <Flex direction={'column'} >
          <Box  css={{mt:0,pt:0,  }}><Subheader css={{mb:0, }}>Advance Learning System Around The World</Subheader></Box>
          <Box css={{mt:0,mb:'6px',color:'#1F6036'  }}><P>We have made a collaborative effort in bringing together scientific expertise from other countries, steered jointly by their governments on the basis of shared, policy-driven interests. </P></Box>
          <Box>
            <Flex>
             <Box>
             <Flex  direction={'column'} css={{borderRight:" 1px solid #D6D6D6", pr:"2.9rem", py:"0", mb:"2rem"}}>
                <Subheader css={{mb:0 ,py:0}}>25k <Sup>+</Sup></Subheader>
                <P css={{mt:0}}>Teachers</P>
              </Flex>
             </Box>
             <Box>
             <Flex  direction={'column'} css={{borderRight:" 1px solid #D6D6D6", pr:"2.9rem",pl: "1.75rem", py:"0", mb:"2rem"}}>
                <Subheader css={{mb:0 ,py:0}}>74k <Sup>+</Sup></Subheader>
                <P css={{mt:0}}>Active Courses</P>
              </Flex>
             </Box>
             <Box>
             <Flex  direction={'column'}css={{pl: "1.75rem", py:"0", mb:"2rem"}}>
                <Subheader css={{mb:0 ,py:0}}>250<Sup css={{color:"White"}} >+</Sup> </Subheader>
                <P css={{mt:0}}>Extra Curriular </P>
              </Flex>
             </Box>
           
              
            </Flex>
          </Box>
          <Box><Button color={'Primary'}>Learn more</Button></Box>
        </Flex></Box>
        <Box css={{ position: "absolute",
                    right: "0",
                    marginTop: "9rem",}}> <img src="/images/mask2.png" alt="" /></Box>
      </Box>
    </Box>
   
  </Container>
</Section>
<Section className='home3' css={{mt:"9.8rem"}}>
  <Box className='home3-main' >
   <Container>
     <Flex direction={'column'}>
       <Box>
         <Flex direction={'column'}  css={{color:"White",justifyContent:"center" }}>
           <Subheader css={{color:"White",mb:0,textAlign:'center'}}>
           Our Features
           </Subheader>
           <P css={{color:"White", mt:"0.94rem",textAlign:'center',width:"50%", alignSelf:"center"}}>Dinny Green International School is nurtured in grace and truth, raising green, flourishing and successful children.
</P>
         </Flex>
       </Box>
       <Box css={{mt:"2.5rem"}}>
       <Features/>
       </Box>
     </Flex>
   </Container>
  </Box>
</Section>

<Section className='home4'>
  <Box className='home4-main' css={{my:"4.25rem" }}>
    <Container  >
      <Box className='dgrid'>
        <Box css={{mt:"5.7rem"}}>
          <Flex direction={'column'} >
            <Subheader>Find Out More About
Our Learning Experience</Subheader>
            <P css={{my:"0.94rem"}}>We have built hospitals, arranged doctor appointments  have the diagnose and treat yourem ipsu r aol ad meniam, quis nostrud exercitation. </P>
            <Box>
              <Flex  alignItems={'center'}>
              <I css={{color:'#038C33', mr:"0.63rem"}} className="fa-solid fa-circle-check icon"></I>
              <P css={{color:" #6C757D"}}>Culture in diversity</P>
              </Flex>
              <Flex  alignItems={'center'}>
              <I css={{color:'#038C33', mr:"0.63rem"}} className="fa-solid fa-circle-check icon"></I>
              <P css={{color:" #6C757D"}}>We have built hospitals, arranged doctor.</P>
              </Flex>
              <Flex  alignItems={'center'}>
              <I css={{color:'#038C33', mr:"0.63rem"}} className="fa-solid fa-circle-check icon"></I>
              <P css={{color:" #6C757D"}}>We have built hospitals, arranged doctor.</P>
              </Flex>
            </Box>
          </Flex>
          <Box css={{mt:"1.88rem"}}> <Button color={'Primary'}>Learn more</Button></Box>
        </Box>
        <Box>
        <Box className="home4-right" >
                    <img
                      src="images\Sect 4 img.png"
                      alt=""
                      className="home4-rightimage"
                    />
                  </Box>
        </Box>
      </Box>
    </Container>

  </Box>
</Section>

<Section  className='home5'>
  <Box  className='home5-main'>
    <Container>
      <Flex >
        <Box>
          <Flex justifyContent={'center'} alignItems={"center"} >
            <Box css={{textAlign:"center",}}>
              <Subheader>Popular Classes</Subheader> 
              <P css={{width:"70%", alignSelf:"center",textAlign:'center'}}>We have built hospitals, arranged doctor appointments  have the diagnose and treat yourem ipsu r aol ad meniam, quis nostrud exercitation.</P>     
                    </Box>
            {/* <Box>icon</Box> */}
          </Flex>
        </Box>
        <Box></Box>
        <Box></Box>
      </Flex>
    </Container>
  </Box>
</Section>
   
</Wrapper>

   </Fragment>
  )
}

export default Home

const Wrapper= styled("div",



{
  '.main':{
  minHeight:"100vh",
  position: 'relative',

  '.banner':
  {
    minHeight:"75vh",
    background:' url("/images/bg1.png")',
    backgroundSize:'cover',
    backgroundRepeat:'no-repeat',
    backgroundPosition:'right',
  },
  '.hero-blur':{ 
    position:'absolute',
    bottom : "0",
    width: '100%',
    background: 'rgba(0, 52, 18, 0.35)',
    backdropFilter: 'blur(33px)',
    
    height: '77px'},
  },
  '.home2':{
   
    '.image-2':{
      position:"relative",
      ".image2-1":{
        position: "absolute",
        top: "1%",
        right: "20%",
        zIndex: "-1",
      },


     
    }
  },
  '.home3':{
    '.home3-main':{
      background: 'url("/images/dinnystudent1.png")',
      backgroundRepeat: 'no-repeat',
      backgroundSize: "cover",
      paddingTop: '4.1rem',
      paddingBottom: '5.9rem',
    
     
    },
      },
      

 
    '.home4-rightimage':{
      position: "absolute",
      right: "0%",
     
    },


  ".dgrid":{
    display: 'grid',
    gridTemplateColumns:" repeat(2,1fr)",
    gap:"50px"
  },
  
  
  '.circle':{
 position: "absolute",
width: "190px",
height: "190px",
 background: "rgba(249, 252, 254, 0.01)",
// backgroundColor:"red",
backdropFilter: "blur(33px)",
 borderRadius: "190px",
left:"42%",
 top:"55%",
  },





  "@media screen and (max-width: 1020px)":{
    '.dgrid':{
      gridTemplateColumns:"repeat(1,1fr)",
      '.banner':{
        
      },
    
    }
  },
})

